@LibraryManagementApp.API_HostAddress = http://localhost:5137

### Get all books
GET {{LibraryManagementApp.API_HostAddress}}/api/Books
Accept: application/json

###

### Create a new book
POST {{LibraryManagementApp.API_HostAddress}}/api/Books
Content-Type: application/json

{
    "title": "Clean Code",
    "author": "Robert C. Martin",
    "isbn": "9780132350884",
    "publishedDate": "2008-08-01"
}

###
